apiVersion: v1
kind: Service
metadata:
  name: zap-service
spec:
  selector:
    app: zap-server
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: gui
      port: 8090
      targetPort: 8090

